#Projet : EcoDefense - Sauver la Terre !
#Auteurs : Adam Hzeg, Alexis Lyonnet, Martin Mechin

LIGNE = 16
COLLONE = 16
GRILLE = 48
PANNEAU_LARGEUR = 300

SCREEN_WIDTH = GRILLE * COLLONE
SCREEN_HEIGHT = GRILLE * LIGNE
FPS = 60
NOMBRE_NIVEAU = 15

NIVEAU_VIE = 100
MONNAIE = 150

#CONSTANTE ENNEMIES
SPAWN_COOLDOWN = 400


#CONSTANTE TOUR
NIVEAU_MAX = 3
NIVEAU_FINI = 20